### PR TITLE
Support file output function callback configuration.

### PR DESCRIPTION
**Pull request by seglo**
Support a function callback for the file option so that you can get access to the target's options object.  This allows you to access the generated option.version and other options more easily.

Excerpt from updated README.md:
#### options.file

Type: `String` | `Function`
Default: _artifactId-version.packaging_
Example: fizzwidget-1.0.0.war

The output file.  You can use either a string or a callback function which takes an `options` parameter.  The `options` parameter includes all the options for this target's configuration.

Example)

``` javascript
function(options) {
  // customize output directory name and filename
  return 'target/' + options.artifactId + '-' + options.version + '.' + options.packaging;
}
```

### CODE REVIEW

**Comment by qualidafial** [comment]
Looks good. Would you modify the documentation to state that if options.snapshot is true, then options.version will already have '-SNAPSHOT' appended to it? Just to avoid confusion.

Edit: options.version will have -SNAPSHOT appended _at the time the file function is invoked_.

**Comment by seglo** [comment]
@qualidafial Thanks for reviewing.  I've pushed the changes you requested.

**Comment by seglo** [comment]
@mrkelly or @qualidafial would it be possible to push a release with these changes?

**Comment by qualidafial** [comment]
@mrkelly What's the game plan on versioning? I see on the develop branch we have a 0.2.0 version. Can I merge this to master and then tag it as 0.2.0?

**Comment by mrkelly** [comment]
@qualidafial I believe 0.2.0 was the last released version.  Since this doesn't break any old configs, I just released it as 0.2.1.  

Do you have an npm account?  I'll add you to the package owners.

**Comment by qualidafial** [comment]
I just set up an account: https://www.npmjs.org/~qualidafial

**Comment by mrkelly** [comment]
:+1:  You should be able to push to NPM now

**Pull request merged**
